-- =============================================================================
-- Correction du set de base : Topps Chrome UEFA Club Competitions 2025-2026
-- product_id = 13b26429-3ca3-4771-8090-e1dea3d0ffc9
--
-- Constat : les 200 cartes de base existantes contenaient des associations
-- numéro / joueur FABRIQUÉES (ex. #188 = Weston McKennie au lieu de
-- James Tavernier, #1 = Mbappé au lieu de Rayan Cherki, etc.).
-- Source officielle utilisée : checklist Cardsmiths Breaks / Beckett.
--   190 cartes "Veterans & Rookies" + 10 "Future Stars" = 200 (#1 à #200).
--
-- Cette migration :
--   1. crée les clubs manquants
--   2. réécrit player_name / team_id / is_rookie des 200 cartes base
--   3. réinitialise image_url (les placeholders contenaient l'ancien nom)
--      -> régénération ensuite via scripts/generate-placeholders.ts
--      -> la seule vraie photo (ancien #1, Mbappé) est transférée sur #112
-- =============================================================================

-- 1. Clubs absents de la base
insert into teams (name)
select v.name
from (values
  ('AFC Ajax'),
  ('Eintracht Frankfurt'),
  ('Nottingham Forest'),
  ('Real Betis Balompié')
) as v(name)
where not exists (select 1 from teams t where t.name = v.name);

-- 2. + 3. Réécriture des 200 cartes base
with incoming(num, player, team, is_rc) as (
  values
    (1,'Rayan Cherki','Manchester City',false),
    (2,'Bernardo Silva','Manchester City',false),
    (3,'Ousmane Dembélé','Paris Saint-Germain',false),
    (4,'Michael Olise','FC Bayern München',false),
    (5,'Jobe Bellingham','Borussia Dortmund',true),
    (6,'Jeremie Frimpong','Liverpool FC',false),
    (7,'Matteo Politano','SSC Napoli',false),
    (8,'Jamaldeen Jimoh-Aloba','Aston Villa',true),
    (9,'Axel Tapé','Bayer 04 Leverkusen',true),
    (10,'Lamine Yamal','FC Barcelona',false),
    (11,'Stanislav Lobotka','SSC Napoli',false),
    (12,'Bukayo Saka','Arsenal FC',false),
    (13,'Antony','Real Betis Balompié',false),
    (14,'João Neves','Paris Saint-Germain',false),
    (15,'Weston McKennie','Juventus',false),
    (16,'Richard Ríos','SL Benfica',true),
    (17,'Jonathan David','Juventus',false),
    (18,'Brennan Johnson','Tottenham Hotspur',false),
    (19,'Gabriel Martinelli','Arsenal FC',false),
    (20,'Iñaki Williams','Athletic Club',false),
    (21,'Ethan Nwaneri','Arsenal FC',false),
    (22,'Senny Mayulu','Paris Saint-Germain',false),
    (23,'Joelinton','Newcastle United',false),
    (24,'Malik Tillman','Bayer 04 Leverkusen',false),
    (25,'Julien Duranville','Borussia Dortmund',false),
    (26,'Robin Mirisola','KRC Genk',true),
    (27,'Christian Kofane','Bayer 04 Leverkusen',true),
    (28,'John McGinn','Aston Villa',false),
    (29,'Kendry Páez','RC Strasbourg Alsace',true),
    (30,'Jota','Celtic FC',false),
    (31,'Eduardo Camavinga','Real Madrid C.F.',false),
    (32,'Shumaira Mheuka','Chelsea FC',true),
    (33,'Savinho','Manchester City',false),
    (34,'Vangelis Pavlidis','SL Benfica',false),
    (35,'Isco','Real Betis Balompié',false),
    (36,'Hugo Larsson','Eintracht Frankfurt',false),
    (37,'Federico Dimarco','FC Internazionale Milano',false),
    (38,'Nico Williams','Athletic Club',false),
    (39,'Dean Huijsen','Real Madrid C.F.',false),
    (40,'Reo Hatate','Celtic FC',false),
    (41,'Scott McTominay','SSC Napoli',false),
    (42,'Viktor Gyökeres','Arsenal FC',false),
    (43,'Sean Steur','AFC Ajax',true),
    (44,'Alejo Sarco','Bayer 04 Leverkusen',true),
    (45,'Mohamed Diomandé','Rangers F.C.',false),
    (46,'Vitinha','Paris Saint-Germain',false),
    (47,'Jérémy Doku','Manchester City',false),
    (48,'Marcus Thuram','FC Internazionale Milano',false),
    (49,'Divine Mukasa','Manchester City',true),
    (50,'William Gomes','FC Porto',false),
    (51,'Cucho','Real Betis Balompié',false),
    (52,'Myles Lewis-Skelly','Arsenal FC',false),
    (53,'Morgan Gibbs-White','Nottingham Forest',false),
    (54,'Robert Lewandowski','FC Barcelona',false),
    (55,'Joshua Kimmich','FC Bayern München',false),
    (56,'Mikey Moore','Rangers F.C.',false),
    (57,'Max Dowman','Arsenal FC',true),
    (58,'Tyrique George','Chelsea FC',false),
    (59,'Serhou Guirassy','Borussia Dortmund',false),
    (60,'Eduardo Felicíssimo','Sporting Clube de Portugal',true),
    (61,'Elye Wahi','Eintracht Frankfurt',false),
    (62,'Martim Fernandes','FC Porto',false),
    (63,'Bradley Barcola','Paris Saint-Germain',false),
    (64,'Jude Bellingham','Real Madrid C.F.',false),
    (65,'Federico Valverde','Real Madrid C.F.',false),
    (66,'Estêvão Willian','Chelsea FC',true),
    (67,'Alexis Mac Allister','Liverpool FC',false),
    (68,'Nick Woltemade','Newcastle United',false),
    (69,'Nuno Mendes','Paris Saint-Germain',false),
    (70,'Reggie Walsh','Chelsea FC',true),
    (71,'Khéphren Thuram','Juventus',false),
    (72,'Ibrahim Maza','Bayer 04 Leverkusen',false),
    (73,'Giovanni Leoni','Liverpool FC',true),
    (74,'Florian Wirtz','Liverpool FC',false),
    (75,'Emiliano Martínez','Aston Villa',false),
    (76,'Romelu Lukaku','SSC Napoli',false),
    (77,'Giovanni Di Lorenzo','SSC Napoli',false),
    (78,'Dominik Szoboszlai','Liverpool FC',false),
    (79,'Virgil van Dijk','Liverpool FC',false),
    (80,'Omar Marmoush','Manchester City',false),
    (81,'Julian Brandt','Borussia Dortmund',false),
    (82,'Antoine Griezmann','Atlético de Madrid',false),
    (83,'Rodrigo Mora','FC Porto',false),
    (84,'Claudio Echeverri','Bayer 04 Leverkusen',true),
    (85,'Xavi Simons','Tottenham Hotspur',false),
    (86,'Endrick','Real Madrid C.F.',false),
    (87,'Gabri Veiga','FC Porto',false),
    (88,'Wisdom Mike','FC Bayern München',true),
    (89,'Mohammed Kudus','Tottenham Hotspur',false),
    (90,'Alphonso Davies','FC Bayern München',false),
    (91,'Victor Froholdt','FC Porto',true),
    (92,'Marquinhos','Paris Saint-Germain',false),
    (93,'Quim Junyent','FC Barcelona',true),
    (94,'Lucas Michal','AS Monaco',true),
    (95,'Geovany Quenda','Sporting Clube de Portugal',false),
    (96,'Elliot Anderson','Nottingham Forest',false),
    (97,'Raphinha','FC Barcelona',false),
    (98,'Daizen Maeda','Celtic FC',false),
    (99,'Nico Schlotterbeck','Borussia Dortmund',false),
    (100,'Giuliano Simeone','Atlético de Madrid',false),
    (101,'Minjae Kim','FC Bayern München',false),
    (102,'Rodrygo','Real Madrid C.F.',false),
    (103,'Phil Foden','Manchester City',false),
    (104,'Ousmane Diomande','Sporting Clube de Portugal',false),
    (105,'Maroan Sannadi','Athletic Club',false),
    (106,'Ricardo Pepi','PSV Eindhoven',false),
    (107,'Andrey Santos','Chelsea FC',false),
    (108,'Nicolò Barella','FC Internazionale Milano',false),
    (109,'Sandro Tonali','Newcastle United',false),
    (110,'Emmanuel Emegha','RC Strasbourg Alsace',false),
    (111,'Dro','FC Barcelona',true),
    (112,'Kylian Mbappé','Real Madrid C.F.',false),
    (113,'William Saliba','Arsenal FC',false),
    (114,'Abdoul Ouattara','RC Strasbourg Alsace',true),
    (115,'Vini Jr.','Real Madrid C.F.',false),
    (116,'Alexander Isak','Liverpool FC',false),
    (117,'Bruno Guimarães','Newcastle United',false),
    (118,'Cole Palmer','Chelsea FC',false),
    (119,'Arthur Theate','Eintracht Frankfurt',false),
    (120,'Ousmane Diallo','Borussia Dortmund',true),
    (121,'Lucas Bergvall','Tottenham Hotspur',false),
    (122,'Noah Adedeji-Sternberg','KRC Genk',true),
    (123,'Takumi Minamino','AS Monaco',false),
    (124,'Ollie Watkins','Aston Villa',false),
    (125,'Ben Parkinson','Newcastle United',true),
    (126,'Jarne Steuckers','KRC Genk',true),
    (127,'Kenneth Taylor','AFC Ajax',false),
    (128,'Karim Adeyemi','Borussia Dortmund',false),
    (129,'George Ilenikhena','AS Monaco',false),
    (130,'Jamal Musiala','FC Bayern München',false),
    (131,'Luis Henrique','FC Internazionale Milano',false),
    (132,'Gavi','FC Barcelona',false),
    (133,'Samu Aghehowa','FC Porto',false),
    (134,'Callum Olusesi','Tottenham Hotspur',true),
    (135,'Frenkie de Jong','FC Barcelona',false),
    (136,'Mohamed Salah','Liverpool FC',false),
    (137,'Omar Janneh','Atlético de Madrid',true),
    (138,'Ferran Torres','FC Barcelona',false),
    (139,'Ivan Perišić','PSV Eindhoven',false),
    (140,'Nasser Djiga','Rangers F.C.',true),
    (141,'Trent Alexander-Arnold','Real Madrid C.F.',false),
    (142,'Reigan Heskey','Manchester City',true),
    (143,'Alessandro Bastoni','FC Internazionale Milano',false),
    (144,'Dominic Solanke','Tottenham Hotspur',false),
    (145,'Denzel Dumfries','FC Internazionale Milano',false),
    (146,'Michael Bresser','PSV Eindhoven',true),
    (147,'Kenan Yildiz','Juventus',false),
    (148,'Alistair Johnston','Celtic FC',false),
    (149,'Abde Ezzalzouli','Real Betis Balompié',false),
    (150,'Konstantinos Karetsas','KRC Genk',true),
    (151,'Mika Godts','AFC Ajax',false),
    (152,'Gleison Bremer','Juventus',false),
    (153,'Patrik Schick','Bayer 04 Leverkusen',false),
    (154,'Julián Alvarez','Atlético de Madrid',false),
    (155,'Tijjani Reijnders','Manchester City',false),
    (156,'Lautaro Martínez','FC Internazionale Milano',false),
    (157,'Martin Ødegaard','Arsenal FC',false),
    (158,'Ibrahim Mbaye','Paris Saint-Germain',false),
    (159,'Anthony Gordon','Newcastle United',false),
    (160,'Leandro Santos','SL Benfica',true),
    (161,'Igor Jesus','Nottingham Forest',true),
    (162,'Mario Götze','Eintracht Frankfurt',false),
    (163,'Pio Esposito','FC Internazionale Milano',true),
    (164,'Declan Rice','Arsenal FC',false),
    (165,'Archie Gray','Tottenham Hotspur',false),
    (166,'Quentin Ndjantou','Paris Saint-Germain',true),
    (167,'Khvicha Kvaratskhelia','Paris Saint-Germain',false),
    (168,'João Rego','SL Benfica',true),
    (169,'Sergiño Dest','PSV Eindhoven',false),
    (170,'Warren Zaïre-Emery','Paris Saint-Germain',false),
    (171,'Rodri','Manchester City',false),
    (172,'Franco Mastantuono','Real Madrid C.F.',true),
    (173,'Don-Angelo Konadu','AFC Ajax',true),
    (174,'Pablo García','Real Betis Balompié',true),
    (175,'Dušan Vlahović','Juventus',false),
    (176,'Hugo Ekitike','Liverpool FC',false),
    (177,'Mathis Amougou','RC Strasbourg Alsace',true),
    (178,'Mika Biereth','AS Monaco',false),
    (179,'Luis Díaz','FC Bayern München',false),
    (180,'Guela Doué','RC Strasbourg Alsace',false),
    (181,'Erling Haaland','Manchester City',false),
    (182,'Harry Kane','FC Bayern München',false),
    (183,'Pau Cubarsí','FC Barcelona',false),
    (184,'João Pedro','Chelsea FC',false),
    (185,'Kang-in Lee','Paris Saint-Germain',false),
    (186,'Chris Wood','Nottingham Forest',false),
    (187,'Lennart Karl','FC Bayern München',true),
    (188,'James Tavernier','Rangers F.C.',false),
    (189,'Conor Gallagher','Atlético de Madrid',false),
    (190,'Guille Fernández','FC Barcelona',true),
    (191,'Rio Ngumoha','Liverpool FC',true),
    (192,'Liam Delap','Chelsea FC',false),
    (193,'Ryan Gravenberch','Liverpool FC',false),
    (194,'Eberechi Eze','Arsenal FC',false),
    (195,'Oihan Sancet','Athletic Club',false),
    (196,'Pedri','FC Barcelona',false),
    (197,'Morgan Rogers','Aston Villa',false),
    (198,'Désiré Doué','Paris Saint-Germain',false),
    (199,'Morten Hjulmand','Sporting Clube de Portugal',false),
    (200,'Kevin De Bruyne','SSC Napoli',false)
)
update cards c
set
  player_name = i.player,
  team_id     = t.id,
  is_rookie   = i.is_rc,
  image_url   = case
    when i.num = 112
      then 'https://tfmaekihhqnouzdtuion.supabase.co/storage/v1/object/public/card-images/111f0161-ae2f-4833-9196-eef8b0525d1e.jpg?v=1781690867087'
    else null
  end
from incoming i
join teams t on t.name = i.team
where c.product_id = '13b26429-3ca3-4771-8090-e1dea3d0ffc9'
  and c.variant_type = 'base'
  and c.card_number = i.num::text;
